# Generated by Django 3.2.3 on 2021-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(max_length=9, unique=True),
        ),
    ]
