# Generated by Django 3.2.3 on 2021-06-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='contraseña',
            new_name='password',
        ),
    ]
